packages:
  - 'projects/*'
  - 'projects/*/server'
  - 'projects/*/web'
  - 'projects/*/e2e'
allowBuilds:
  '@nestjs/core': false
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - zustand@5.0.14
