import { z } from 'zod';

/**
 * Tick payload — one frame per Binance Futures aggTrade fanned out to the
 * browser. Drives the live tape ticker strip in the chart UI.
 *
 * This is the BROWSER-facing tick shape, intentionally distinct from the
 * Rust↔Bun bridge `TickFrame` type generated by `ts-rs` and from the
 * persisted Drizzle `ticks` row. The bridge shape uses Rust `i64` for
 * `ts_ms` which `ts-rs` maps to `bigint` on the TS side; the persisted
 * row uses Postgres `bigint`. We deliberately drop down to `number`
 * (JS f64) on the WS wire for three reasons:
 *
 *  1. **Int53 safety.** A 13-digit millisecond timestamp (`Date.now()`)
 *     lives in [1e12, 1e13). `Number.MAX_SAFE_INTEGER ≈ 9.007e15` — every
 *     ms timestamp this product will ever emit is exactly representable
 *     as f64. We get the full nominal range until the year 287396, well
 *     past the demo URL's commercial-seed thesis.
 *  2. **Renderer ergonomics.** The Canvas2D footprint chart and the tape
 *     ticker render to integer pixels; their entire math lane is f64.
 *     Carrying `bigint` to the boundary would force a `Number(...)`
 *     coercion in the hot path of every consumer for zero correctness
 *     win at this range.
 *  3. **msgpackr decode shape.** msgpackr decodes MessagePack `int`
 *     family values as `number` when they fit `Number.MAX_SAFE_INTEGER`
 *     by default. The WS-side codec stays at the default; the bridge-side
 *     codec was configured for `bigint` decode because the Rust struct
 *     uses `i64`. Same library, different boundary policies — documented
 *     in `AGENT_NOTES.md` so the two do not get "harmonised".
 *
 * The bigint-vs-number trade-off resurfaces if a future feature carries
 * nanosecond-precision exchange timestamps (Binance Futures' `T` field
 * is ms-level today). At ns precision (~16 digits) f64 starts losing
 * the trailing nanoseconds and a `bigint` payload field becomes
 * mandatory. v2 conversation, not v1.
 *
 * Field map:
 *  - `tsMs`      — Binance trade time, ms since epoch. Positive int.
 *  - `price`     — Trade price. Positive finite f64.
 *  - `qty`       — Trade quantity. Positive finite f64.
 *  - `aggressor` — `'buy'` (market buy, taker = buyer) or `'sell'`
 *                  (market sell, taker = seller). Lowercase ASCII per
 *                  CLAUDE.md § 2 "English only, no emojis".
 */
export const wsTickPayloadSchema = z.object({
  tsMs: z.number().int().positive(),
  price: z.number().positive(),
  qty: z.number().positive(),
  aggressor: z.enum(['buy', 'sell']),
});

export type WSTickPayload = z.infer<typeof wsTickPayloadSchema>;
