import { barberSchema, type Barber } from '@/lib/schemas/barber';
import type { WeeklySchedule } from '@/lib/schemas/barber';

import { BLUR_PLACEHOLDERS } from './image-placeholders';
import { BARBER_BIOS } from './seed-data';
import { SERVICES } from './services';

/**
 * The fixed Razor's Edge barber roster (ADR-003 / PLAN.md).
 *
 * Identities, specialties, working hours, days-off, and lunch are
 * hand-curated so the roster reads as a real team with distinct schedules
 * (giving the availability grid believable gaps). Faker — seeded for
 * determinism (docs/conventions.md § 6) — fills ONLY the bio flavour copy.
 *
 * Days-off are pinned to concrete dates inside the frozen "next 14 days"
 * window (frozen now = Wed 2026-06-10) so the grid shows real day-off
 * holes deterministically.
 *
 * `serviceIds` are derived from each barber's `specialties` against the
 * fixed menu, so a barber's bookable services always stay consistent with
 * what they specialise in.
 *
 * The bios were generated by faker (seed 74017) at build time and BAKED into
 * the static `seed-data.ts` module (`BARBER_BIOS`). faker is NOT imported
 * here at runtime — it uses `new Function`/`eval` internally, which the
 * strict CSP blocks, and this module is reached by the booking wizard's
 * client components. The baked bios are byte-identical to the seeded output.
 */

/** Indexed 0 = Sun … 6 = Sat (matches WeeklySchedule / clock weekday). */
function schedule(
  rows: Partial<Record<number, { open: string; close: string }>>,
): WeeklySchedule {
  const day = (i: number) => rows[i] ?? null;
  return [day(0), day(1), day(2), day(3), day(4), day(5), day(6)];
}

const STANDARD_WEEK = schedule({
  // Closed Sun + Mon (a luxe studio's quiet days), Tue–Sat trading.
  2: { open: '10:00', close: '18:00' },
  3: { open: '10:00', close: '18:00' },
  4: { open: '10:00', close: '20:00' },
  5: { open: '10:00', close: '20:00' },
  6: { open: '09:00', close: '16:00' },
});

const LATE_WEEK = schedule({
  // The late-shift barber: midweek into the evening, off Tue.
  3: { open: '12:00', close: '20:00' },
  4: { open: '12:00', close: '20:00' },
  5: { open: '12:00', close: '21:00' },
  6: { open: '10:00', close: '18:00' },
  0: { open: '11:00', close: '16:00' }, // open Sundays
});

const EARLY_WEEK = schedule({
  // The early-shift barber: opens the studio, off Thu–Fri.
  1: { open: '08:00', close: '15:00' },
  2: { open: '08:00', close: '15:00' },
  3: { open: '08:00', close: '15:00' },
  6: { open: '08:00', close: '14:00' },
});

function serviceIdsFor(specialties: Barber['specialties']): string[] {
  return SERVICES.filter((s) => specialties.includes(s.category)).map(
    (s) => s.id,
  );
}

interface BarberSeed {
  id: string;
  slug: string;
  name: string;
  handle: string;
  title: string;
  specialties: Barber['specialties'];
  workingHours: WeeklySchedule;
  daysOff: string[];
  lunch?: { startMin: number; durationMin: number };
  portraitAspect: number;
}

const RAW_BARBERS: BarberSeed[] = [
  {
    id: 'brb-marco',
    slug: 'marco-vidal',
    name: 'Marco Vidal',
    handle: '@marco.vidal',
    title: 'Master Barber & Founder',
    specialties: ['cut', 'beard', 'shave', 'combo'],
    workingHours: STANDARD_WEEK,
    daysOff: ['2026-06-13'], // Sat off this week
    lunch: { startMin: 13 * 60, durationMin: 45 }, // 13:00–13:45
    portraitAspect: 0.8,
  },
  {
    id: 'brb-idris',
    slug: 'idris-bello',
    name: 'Idris Bello',
    handle: '@idris.fades',
    title: 'Senior Barber — Fades & Beard',
    specialties: ['cut', 'beard', 'combo'],
    workingHours: STANDARD_WEEK,
    daysOff: ['2026-06-11'], // Thu off
    lunch: { startMin: 14 * 60, durationMin: 30 }, // 14:00–14:30
    portraitAspect: 0.8,
  },
  {
    id: 'brb-sasha',
    slug: 'sasha-ren',
    name: 'Sasha Ren',
    handle: '@sasha.ren',
    title: 'Barber — Cuts & Restyles',
    specialties: ['cut', 'combo'],
    workingHours: LATE_WEEK,
    daysOff: ['2026-06-19'],
    lunch: { startMin: 16 * 60, durationMin: 30 }, // 16:00–16:30
    portraitAspect: 0.8,
  },
  {
    id: 'brb-emil',
    slug: 'emil-novak',
    name: 'Emil Novak',
    handle: '@emil.straightrazor',
    title: 'Barber — Straight-Razor Specialist',
    specialties: ['shave', 'beard', 'combo'],
    workingHours: STANDARD_WEEK,
    daysOff: ['2026-06-12'], // Fri off
    lunch: { startMin: 13 * 60 + 30, durationMin: 30 }, // 13:30–14:00
    portraitAspect: 0.8,
  },
  {
    id: 'brb-jonah',
    slug: 'jonah-pike',
    name: 'Jonah Pike',
    handle: '@jonah.opens',
    title: 'Junior Barber — Early Shift',
    specialties: ['cut', 'beard'],
    workingHours: EARLY_WEEK,
    daysOff: ['2026-06-16'],
    portraitAspect: 0.8,
  },
];

function buildBarber(seed: BarberSeed): Barber {
  const bio = BARBER_BIOS[seed.id] ?? `${seed.name}, a Razor's Edge barber.`;

  return barberSchema.parse({
    id: seed.id,
    slug: seed.slug,
    name: seed.name,
    handle: seed.handle,
    title: seed.title,
    bio,
    specialties: seed.specialties,
    serviceIds: serviceIdsFor(seed.specialties),
    portrait: {
      slot: `barber-${seed.slug}`,
      src: `/images/graded/barber-${seed.slug}.jpg`,
      alt: `${seed.name}, ${seed.title} at Razor's Edge`,
      aspectRatio: seed.portraitAspect,
      blurDataURL:
        BLUR_PLACEHOLDERS[
          `barber-${seed.slug}` as keyof typeof BLUR_PLACEHOLDERS
        ],
    },
    workingHours: seed.workingHours,
    daysOff: seed.daysOff,
    ...(seed.lunch ? { lunch: seed.lunch } : {}),
  });
}

/** The validated, frozen roster. */
export const BARBERS: readonly Barber[] = Object.freeze(
  RAW_BARBERS.map(buildBarber),
);

export function getBarberById(id: string): Barber | undefined {
  return BARBERS.find((b) => b.id === id);
}

export function getBarberBySlug(slug: string): Barber | undefined {
  return BARBERS.find((b) => b.slug === slug);
}

/** Barbers who perform a given service category (wizard barber filtering). */
export function barbersForCategory(
  category: Barber['specialties'][number],
): Barber[] {
  return BARBERS.filter((b) => b.specialties.includes(category));
}
