/* AUTO-GENERATED by scripts/grade-photography.mjs — do not edit by hand. */
/* Base64 blur placeholders (LQIP) for the graded photography set. */
export const BLUR_PLACEHOLDERS = {
  "hero-desktop": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoQAAoAA4BaJYwCdAENgWYIDcAA/vkS+HL7zRL67dvNWyeh5XKsElKxhgAAAA==",
  "hero-mobile": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoQABUAPu1mq04ppaQiMAgBMB2JQBdgBDeQzqiGV4FeaF8AAP70JSRg4mD9WCDNG8Kv6hZ70IPfobtQeZQWN03Xi9kbhlTFQ/0AD3PlGQAck9hH4AAAAA==",
  "gallery-01": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwBACdASoQABQAPu1iqk4ppaQiMAgBMB2JYwCdMoADTnzb+d9U2UGBKnAA/vM0z0r2U98eSvuW52x8itUv3uLuD7LUW0u868Y6Kz3ozlcCQrjYG5gAAA==",
  "gallery-02": "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAACQAQCdASoQAAsAA4BaJZwAAudHyhgA/vkTAjIbzn6l8TMoy8AAAA==",
  "gallery-03": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAAAQAgCdASoQAAkAA4BaJYwCdAERH0BvLLUAAP717hlXhXXGul+JLU9vmx2SWW+dwAA=",
  "gallery-04": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JYwCdMoACqFAoVOlqIwAA/quaZDu8tKb2jJrrZpOCzHuF4L0Zq//2KuUmMT0tHHISzw32XSaAAA==",
  "gallery-05": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAQAgCdASoQAAsAA4BaJQBWACHgUpQvI3UAAP7y6rHP8K0YKNq3d2bxVRTM0TD3DLjAV3cnJ9WAAA==",
  "barber-marco-vidal": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZQC7ABugivXCyR8AAP70MtwrxxD+woxN7ggfOclpO7p30/ZvwIHmNQnwAAAA",
  "barber-idris-bello": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACQAwCdASoQABQAPu1iqk2ppaQiMAgBMB2JQBOmUABk5WpgSOnAAP6pmtZJt5j9JaWzHGLPIm9oQj0jk6N5Xul1BOKYYS3N/fWZDBcbbUE7VEpC/LtVgAAA",
  "barber-sasha-ren": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQBACdASoQABQAPu1iqU2ppaQiMAgBMB2JQBOmUABG9ugMYhG0+WzRQAD40peTyedFBS2UwMSySxBkq5XBCBHZbSfmzWKTatgoIs3LC+QWxCjZQ5NQAA==",
  "barber-emil-novak": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABwAwCdASoQABQAPu1iqU2ppaQiMAgBMB2JZwDImCHEogmCBQAA/vQjgRTyouRojTC4nfnDER0REFmTogA=",
  "barber-jonah-pike": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQBACdASoQABQAPu1kqU4ppaOiMAgBMB2JZgCdACHSxz2VAS7LrmKwAAD+6/VjcGlD/VxNDWp0dSig/gIaFeCHPt8bpN321zNB8chQaJ9gPuXj/eyh8AAA"
} as const;
export type GradedImageName = keyof typeof BLUR_PLACEHOLDERS;
