import { preBookingSchema, type PreBooking } from '@/lib/schemas/availability';

import { SEEDED_PRE_BOOKINGS } from './seed-data';

/**
 * Seeded pre-bookings (ADR-003) — a believable set of existing appointments
 * per barber so the availability grid has realistic gaps, deterministic
 * across reloads.
 *
 * The set was generated by the faker-driven factory (seed 91135) at BUILD
 * time — walking the frozen "next 14 days" and placing 0–3 grid-aligned,
 * non-overlapping bookings per barber per open day — and BAKED into the
 * static `seed-data.ts` (`SEEDED_PRE_BOOKINGS`). faker is NOT imported here
 * at runtime: it uses `new Function`/`eval` internally, which the strict CSP
 * blocks, and this module is reached by the booking wizard's client
 * components (the availability reconciliation). The baked array is the exact
 * seeded output; we re-validate it through the schema so a bad row still
 * fails loud. To regenerate, run the `__generate__` test + `bake-seed.mjs`.
 */

/** The validated, frozen seeded pre-booking set. */
export const PRE_BOOKINGS: readonly PreBooking[] = Object.freeze(
  SEEDED_PRE_BOOKINGS.map((b) => preBookingSchema.parse(b)),
);

export function preBookingsForBarber(barberId: string): PreBooking[] {
  return PRE_BOOKINGS.filter((b) => b.barberId === barberId);
}
