import {
  testimonialSchema,
  type Testimonial,
} from '@/lib/schemas/testimonial';

import { TESTIMONIAL_AUTHORS } from './seed-data';

/**
 * Seeded testimonials (ADR-003) — a curated set of client quotes presented
 * editorially (not a star-rating dump). Quotes are hand-written for tone;
 * the author names were generated by faker (seed 20544) at build time and
 * BAKED into the static `seed-data.ts` (`TESTIMONIAL_AUTHORS`). faker is NOT
 * imported here — it uses `new Function`/`eval` internally, which the strict
 * CSP blocks, and the `@/mocks` barrel (which re-exports this) is reached by
 * the booking wizard's client components. The baked authors are identical
 * to the seeded output.
 */

interface TestimonialSeed {
  id: string;
  rating: 1 | 2 | 3 | 4 | 5;
  quote: string;
  service?: string;
}

const RAW: TestimonialSeed[] = [
  {
    id: 'tst-01',
    rating: 5,
    quote:
      'The first place that asked what I wanted before reaching for the clippers. Best cut I have had in years.',
    service: 'Signature Cut',
  },
  {
    id: 'tst-02',
    rating: 5,
    quote:
      'The hot-towel shave is a whole ritual. I came in for a tidy-up and left feeling like a different man.',
    service: 'Hot-Towel Straight Shave',
  },
  {
    id: 'tst-03',
    rating: 5,
    quote:
      'Idris reads a head shape like nobody else. The fade was flawless and still looked sharp three weeks later.',
    service: 'Skin Fade',
  },
  {
    id: 'tst-04',
    rating: 4,
    quote:
      'Unhurried, precise, and the room itself is worth the visit. The brass and low light set the tone.',
    service: 'Cut & Beard',
  },
  {
    id: 'tst-05',
    rating: 5,
    quote:
      'Booked The Works for my wedding morning. Two hours of being looked after and the photos prove it was worth it.',
    service: 'The Works',
  },
  {
    id: 'tst-06',
    rating: 5,
    quote:
      'My beard has never been this tidy. They actually shape it to my face instead of just running a trimmer over it.',
    service: 'Beard Sculpt',
  },
  {
    id: 'tst-07',
    rating: 4,
    quote:
      'Easy to book, on time, and the result speaks for itself. This is the new regular.',
  },
  {
    id: 'tst-08',
    rating: 5,
    quote:
      'Emil with a straight razor is the closest shave I have ever had. Worth every grosz.',
    service: 'Hot-Towel Straight Shave',
  },
];

function buildTestimonial(seed: TestimonialSeed): Testimonial {
  const author = TESTIMONIAL_AUTHORS[seed.id] ?? 'A client';
  return testimonialSchema.parse({
    id: seed.id,
    author,
    rating: seed.rating,
    quote: seed.quote,
    ...(seed.service ? { service: seed.service } : {}),
  });
}

/** The validated, frozen testimonial set. */
export const TESTIMONIALS: readonly Testimonial[] = Object.freeze(
  RAW.map(buildTestimonial),
);
