import type { Metadata, Viewport } from 'next';
import { Inter, Space_Grotesk } from 'next/font/google';
import type { ReactNode } from 'react';

import { SITE_DESCRIPTION, SITE_NAME, SITE_URL } from '@/lib/site-config';
// Side-effect FIRST (ADR-002 §5): configure zod jitless at the root of every
// route's module graph so no validator on any route can JIT-compile a
// `new Function` probe under the strict no-`unsafe-eval` CSP.
import '@/lib/zod-config';

import { SiteFooter } from '@/components/chrome/site-footer';
import { SiteHeader } from '@/components/chrome/site-header';

import { Providers } from './providers';

import './globals.css';

/* -------------------------------------------------------------------------
 * Root layout — APEX shell.
 *
 * Fonts (Task 2.2): two OFL-licensed VARIABLE faces, self-hosted by next/font
 * (no runtime Google request — CSP-clean, no third-party `font-src`):
 *   - Inter        → `--font-apex-sans`    (UI + body; technological neutral
 *                     grotesk with a real weight axis for font-variation use)
 *   - Space Grotesk → `--font-apex-display` (APEX wordmark + section heads; a
 *                     geometric, slightly mechanical display cut with intent)
 * Both expose CSS variables bound on <html>; globals.css `--font-sans` /
 * `--font-display` reference them with a system fallback (next/font adds
 * `size-adjust` metrics so the fallback swap does not shift layout).
 *
 * `<html>` carries `suppressHydrationWarning` because next-themes mutates the
 * class on the client before React hydrates (the documented next-themes
 * pattern). LIGHT is the canonical default, so the server renders the light
 * token set from :root and there is no dark flash.
 *
 * The persistent chrome (sticky header, footer) is mounted here (Task 4.1).
 * The track-line divider is a per-section component (used by the configurator
 * placeholder + footer + Phase-5 sections).
 * --------------------------------------------------------------------- */

/**
 * Inter — variable sans for UI + body. OFL-1.1 (SIL Open Font License).
 * `axes: ['opsz']` keeps the optical-size axis available alongside the default
 * weight axis so `font-variation-settings` hooks can tune weight + opsz.
 */
const apexSans = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-apex-sans',
  axes: ['opsz'],
});

/**
 * Space Grotesk — variable display cut for the APEX wordmark + section heads.
 * OFL-1.1. Ships a weight axis (300–700) used for the wordmark lockups.
 */
const apexDisplay = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-apex-display',
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_NAME,
    template: `%s — ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: [
    'EV rental',
    'electric vehicle rental',
    'car rental',
    'premium rental',
    'reserve',
  ],
  authors: [{ name: 'Jan Antczak' }],
  alternates: {
    canonical: '/',
  },
  openGraph: {
    type: 'website',
    url: '/',
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
    siteName: SITE_NAME,
    locale: 'en_GB',
    // P1-1: a real 1200×630 share card (generated by `scripts/generate-og-image.mjs`
    // from the flagship studio render; PNG for universal crawler support). The
    // image is a same-origin static asset (covered by `img-src 'self'`).
    images: [
      {
        url: '/og/opengraph.png',
        width: 1200,
        height: 630,
        alt: 'APEX — premium electric vehicle rental with a 3D configurator',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
    images: ['/og/opengraph.png'],
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#f4f6f8' },
    { media: '(prefers-color-scheme: dark)', color: '#0a0e14' },
  ],
  width: 'device-width',
  initialScale: 1,
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps): ReactNode {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${apexSans.variable} ${apexDisplay.variable}`}
    >
      <body className="antialiased">
        <Providers>
          <a
            href="#main"
            className="sr-only z-50 rounded-md px-4 py-2 focus:not-sr-only focus:fixed focus:top-4 focus:left-4"
            style={{
              backgroundColor: 'var(--color-surface)',
              color: 'var(--color-foreground)',
            }}
          >
            Skip to content
          </a>
          {/* Persistent chrome (Task 4.1): the sticky header is transparent over
              the hero and gains its backdrop after; the footer closes every
              page. The header floats over `main` (it is `fixed`), so the hero
              owns the first viewport and the header appears/sticks after it. */}
          <SiteHeader />
          {children}
          <SiteFooter />
        </Providers>
      </body>
    </html>
  );
}
